# -*- coding: utf-8 -*-
"""Conversion

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HoYQuBiwzWpZ_lIS5A-yJIgpz30zNUDL
"""


import torch
import chess
from chess import pgn
from chess import Board

channels = {
    "wp": 0,
    "bp": 1,
    "wn": 2,
    "bn": 3,
    "wb": 4,
    "bb": 5,
    "wk": 6,
    "bk": 7,
    "wr": 8,
    "br": 9,
    "wq": 10,
    "bq": 11,
    "wkc": 12,
    "wqc": 13,
    "bkc": 14,
    "bqc": 15,
    "ep": 16,
    "stm": 17
}

piece_labels = {
    chess.PAWN: "p",
    chess.KNIGHT: "n",
    chess.BISHOP: "b",
    chess.ROOK: "r",
    chess.QUEEN: "q",
    chess.KING: "k"
}
def represent(board: Board):
  matrix = torch.zeros((18,8,8))
  map = board.piece_map()
  for key in map:
    piece_type = map[key].piece_type
    piece_color = map[key].color
    suffix = piece_labels[piece_type]
    prefix = "w" if piece_color else "b"
    channel = channels[prefix + suffix]
    row = 7 - key//8
    col = key % 8
    matrix[channel,row,col] = 1
  if board.turn == chess.WHITE:
        matrix[channels["stm"], :, :] = 1
  if board.has_kingside_castling_rights(chess.WHITE):
        matrix[channels["wkc"], :, :] = 1
  if board.has_queenside_castling_rights(chess.WHITE):
        matrix[channels["wqc"], :, :] = 1
  if board.has_kingside_castling_rights(chess.BLACK):
        matrix[channels["bkc"], :, :] = 1
  if board.has_queenside_castling_rights(chess.BLACK):
        matrix[channels["bqc"], :, :] = 1
  if board.ep_square is not None:
        ep_row = 7 - (board.ep_square // 8)
        ep_col = board.ep_square % 8
        matrix[channels["ep"], ep_row, ep_col] = 1
  move_matrix = torch.zeros((64,64))
  return matrix

